name: build

on:  
  push:
    paths-ignore:
    - "README.md"
    - "docs/**"
    branches:
    - main

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - name: BOSS Update packages
      run: boss update

    - name: Creating output folders
      run: |
        mkdir bin
        mkdir bin/linux
        mkdir bin/windows
        mkdir bin/macos
        
    - name: Building & testing (Linux)
      run: |
        echo "building main application..."
        ~/laz-222/lazarus/lazbuild "pasc.lpi" --build-mode=Release
        cp ./pasc ./bin/linux/pasc
        echo "building tests"
        ~/laz-222/lazarus/lazbuild "tests/TestPasc.lpi"
        cp ./tests/TestPasc ./bin/linux/TestPasc
        cp ./tests/TestPasc.lpr ./bin/linux/TestPasc.lpr
        ./bin/linux/TestPasc "--all" "--format=plain"
