name: build

on:  
  push:
    paths-ignore:
    - "README.md"
    - "docs/**"
    branches:
    - main

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - name: BOSS Update packages
    run: boss update
        
    - name: Build the Main Application 
      run: ~/laz-222/lazarus/lazbuild "pasc.lpi" --build-mode=Release
    
    - name: Build the Unit Tests Application 
      run: ~/laz-222/lazarus/lazbuild "tests/TestPasc.lpi"
    
    - name: Run the Unit Tests Application
      run: tests/TestPasc "--all" "--format=plain"
