name: build

on:  
  push:
    paths-ignore:
    - "README.md"
    - "docs/**"
    branches:
    - main

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - name: BOSS Update packages
      run: boss update

    - name: Creating output folders
      run: |
        mkdir bin
        mkdir bin/linux
        mkdir bin/linux/tests
        mkdir bin/windows
        mkdir bin/windows/tests
        mkdir bin/macos
        mkdir bin/macos/tests
        
    - name: Building & testing (Linux)
      run: |
        echo "building main application..."
        ~/laz-222/lazarus/lazbuild "pasc.lpi" -B --build-mode=Release
        cp ./pasc ./bin/linux/pasc
        echo "building tests"
        ~/laz-222/lazarus/lazbuild "tests/TestPasc.lpi" -B 
        cp ./tests/TestPasc ./bin/linux/tests/TestPasc
        echo "running tests and change the current folder"
        ./tests/TestPasc "--all" "--format=plain"

    - name: Building & testing (Windows)
      run: |
        echo "building main application..."
        ~/laz-222/lazarus/lazbuild "pasc.lpi" -B --build-mode=Release --os=Win64 --cpu=x86_64
        cp ./pasc.exe ./bin/windows/pasc.exe
        echo "building tests"
        ~/laz-222/lazarus/lazbuild "tests/TestPasc.lpi" -B --os=Win64 --cpu=x86_64
        cp ./tests/TestPasc.exe ./bin/windows/tests/TestPasc.exe

    - name: Building & testing (MacOs)
      run: |
        echo "building main application..."
        ~/laz-222/lazarus/lazbuild "pasc.lpi" -B --build-mode=Release --os=darwin
        cp ./pasc ./bin/macos/pasc
        echo "building tests"
        ~/laz-222/lazarus/lazbuild "tests/TestPasc.lpi" -B --os=darwin
        cp ./tests/TestPasc ./bin/macos/tests/TestPasc
