name: build

on:  
  push:
    paths-ignore:
    - "README.md"
    - "docs/**"
    - ".github/workflows/deploy.yml"
    branches:
    - "main"

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest,windows-latest]
        lazarus-versions: [stable]
    steps:
    - uses: actions/checkout@v3

    - name: Install Lazarus
      uses: gcarreno/setup-lazarus@v3
      with:
        lazarus-version: ${{ matrix.lazarus-versions }}
        with-cache: true

    - name: Download and extract BOSS (Linux)
      if: ${{ matrix.operating-system == 'ubuntu-latest' }}
      run: |
        curl -LOk https://github.com/HashLoad/boss/releases/download/v3.0.10/boss-linux-amd64.zip
        unzip boss-linux-amd64.zip
        chmod +x ./linux-amd64/boss
        echo "$GITHUB_WORKSPACE/linux-amd64" >> $GITHUB_PATH

    - name: Download and extract BOSS (Windows)
      if: ${{ matrix.operating-system == 'windows-latest' }}
      run: |
        curl -LOk https://github.com/HashLoad/boss/releases/download/v3.0.10/boss-windows-amd64.zip
        unzip boss-windows-amd64.zip
        echo (Join-Path $env:GITHUB_WORKSPACE "windows-amd64") | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: BOSS Update packages
      run: boss update
        
    - name: Building main application
      run: |
        echo "building main application..."
        lazbuild "pasc.lpi" -B --build-mode=Release

    - name: Building unit test application
      run: |
        echo "building main application..."
        lazbuild "tests/TestPasc.lpi" -B

    - name: Run the unit test application
      run: |
        echo "running unit tests..."
        tests/TestPasc "--all" "--format=plain"